name: 'Study'
description: 'Sou o Techlead da Studywise'
author: 'Studywise'
inputs:
  token:
    description: 'GitHub token'
    default: $
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
